#Do not change the value of these variables at all

#Successful responses codes
HTTP_STATUS_OK = 200
HTTP_STATUS_CREATED = 201
HTTP_STATUS_ACCEPTED = 202

#Client error responses codes
HTTP_STATUS_BAD_REQUEST = 400
HTTP_STATUS_UNATHORIZED = 401
HTTP_STATUS_FORBIDDEN = 403
HTTP_STATUS_NOT_FOUND = 404

#Internal Server Error
HTTP_STATUS_INTERNAL_SERVER_ERROR = 500

