from collections import namedtuple

#Successful responses codes
# HTTP_STATUS_OK = 200
# HTTP_STATUS_CREATED = 201
# HTTP_STATUS_ACCEPTED = 202

#Client error responses codes
# HTTP_STATUS_BAD_REQUEST = 400
# HTTP_STATUS_UNATHORIZED = 401
# HTTP_STATUS_FORBIDDEN = 403
# HTTP_STATUS_NOT_FOUND = 404

#Internal Server Error
# HTTP_STATUS_INTERNAL_SERVER_ERROR = 500
# HTTP_STATUS_SERVICE_NOT_AVAILABLE = 503

Status = namedtuple('Status', ['HTTP_STATUS_OK', 'HTTP_STATUS_CREATED',
'HTTP_STATUS_ACCEPTED', 'HTTP_STATUS_BAD_REQUEST', 'HTTP_STATUS_UNATHORIZED',
'HTTP_STATUS_FORBIDDEN', 'HTTP_STATUS_NOT_FOUND', 'HTTP_STATUS_INTERNAL_SERVER_ERROR', 
'HTTP_STATUS_SERVICE_NOT_AVAILABLE'])


STATUS_CODES: int = Status(200, 201, 202, 400, 401, 403, 404, 500, 503)


