openapi: 1.0.0
info:
  title: Widget Builder
  description: Builds widgets and and stores them in a database
  version: 0.1

servers:
  - url: http://localhost:3000/
    description: Homepage for assessment

paths:
  /create_widget:
    post:
      summary: creates a widget and stores it in database
      requestBody: 
        required: true
        content:
          application/json:
           schema:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              num_of_parts:
                type: integer
      responses:
        '201':
          description: Created widget successfully
        '400':
          description: No request body was sent or number of values in req body not correct
        '500':
          description: Did not create widget 

  /get_widget:
    get:
      summary: gets a single widget object from database
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                id:
                  type: string
      responses:
        '200':
          description: database was read from correctly
        '400': 
          description: No request body was sent or number of values in req body not correct
        '500':
          description: resource couldn't be retrieved
  
  /get_list_of_widgets:
    get:
      summary: gets a list of widgets from database based on num_of_parts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                num_of_parts:
                  type: integer
      responses:
        '200':
          description: database was read from correctly
        '400': 
          description: No request body was sent or number of values in req body not correct 
        '500':
          description: error in getting list from database

  /update_widget:
    put:
      summary: updates a widget object stored in database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: 
                id:
                  type: string
                name:
                  type: string
                num_of_parts:
                  type: integer
        responses:
          '200': 
            description: widget was successfully updated
          '400': 
            description: No request body was sent or number of values in req body not correct
          '400':
            description: could not update widget

  /delete_widget
    delete:
      summary: deletes widget from database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
      responses:
        '200':
          description: Widget was succesfully deleted
        '400':
          description: No request body was sent or number of values in req body not correct
        '500':
          description: Error deleting widget

  

